version: "3.9"
services:
  postgres:
    container_name: subscriptions_database
    image: "postgres:13.2-alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
